Milly:
  CrudUI:
    entities:
      Milly\CrudUI\Showcase\Domain\Model\Artist:
        label:
          one: Artist
          many: Artists
        properties:
          name: []
          biography:
            type: textarea
          styles:
            type: multiSelect
            options:
              repository: Milly\CrudUI\Showcase\Domain\Repository\StyleRepository
        relations:
          albums:  []
        views:
          index:
            properties: [name, styles]
            orderBy: [name]
            showColumnHeaders: true
