Milly:
  CrudUI:
    entities:
      Milly\CrudUI\Showcase\Domain\Model\Track:
        parent: album
        label:
          one: Track
          many: Tracks
        properties:
          title: []
          audio:
            type: audio
