Neos:
  Neos:
    modules:
      milly:
        label: Milly.CrudUI
        controller: Neos\Neos\Controller\Module\ManagementController
        position: 'after content'
        icon: 'far fa-list-alt'
        submodules:
          music:
            label: 'Music'
            controller: Milly\CrudUI\Showcase\Controller\Backend\ArtistController
            description: ''
            icon: 'fas fa-compact-disc'
            additionalResources:
              styleSheets:
                - 'resource://Milly.CrudUI/Public/Css/neosBackend.css'
